- name: "Wait for VM to be in ready state"
  uri:
    url: "{{ vcd_vm_href }}"
    method: GET
    headers:
      Accept: "application/*+xml;version=39.0"
      x-vcloud-authorization: "{{ vcd_auth_token }}"
    validate_certs: "{{ vcd_validate_certs | default(true) }}"
    timeout: "{{ vcd_api_timeout | default(30) }}"
  register: vcd_vm_ready_response
  until: |
    (vcd_vm_ready_response.content | regex_search('status="4"')) and
    (not (vcd_vm_ready_response.content | regex_search('deployed="false"')))
  retries: "{{ vcd_vm_ready_retries | default(30) }}"
  delay: "{{ vcd_vm_ready_delay | default(10) }}"